server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      server-addr: 192.168.150.66:1111 # Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露端口
